# Generated by Django 4.1.3 on 2022-11-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=10)),
                ("number_of_pages", models.IntegerField()),
                ("publish_date", models.DateField()),
                ("quantity", models.IntegerField()),
            ],
        ),
    ]
